server:
  port: 1002
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeoLeeWithWarmPants/SC-config
          username: 512240816@qq.com
          password: lyl512240816
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
